# Generated by Django 5.1.1 on 2025-01-11 06:41

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0005_event_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
