# Generated by Django 5.1.1 on 2025-01-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0006_alter_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(),
        ),
    ]
