# Generated by Django 5.1.1 on 2025-01-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0008_userevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="final_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
