# Generated by Django 5.1.1 on 2025-01-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0009_event_final_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="final_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
